# Generated by Django 2.2.10 on 2020-08-03 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос с одним вариантом ответа',
                'verbose_name_plural': 'Вопросы с одним вариантом ответа',
            },
        ),
        migrations.CreateModel(
            name='MultiChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос с несколькими вариантами',
                'verbose_name_plural': 'Вопросы с несколькими вариантами',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='SimpleQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Ответ текстом',
                'verbose_name_plural': 'Ответы текстом',
            },
        ),
        migrations.CreateModel(
            name='SimpleAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True, verbose_name='ID пользователя')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.SimpleQuestion', verbose_name='Простой вопрос')),
            ],
            options={
                'verbose_name': 'Ответ текстом',
                'verbose_name_plural': 'Ответы текстом',
            },
        ),
        migrations.CreateModel(
            name='MultiChoiceQuestionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_value', models.TextField(verbose_name='Вариант ответа')),
                ('choice_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.MultiChoiceQuestion', verbose_name='Вопрос с множественным выбором')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Вариант ответа',
            },
        ),
        migrations.AddField(
            model_name='multichoicequestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz', verbose_name='Опрос'),
        ),
        migrations.CreateModel(
            name='MultiChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True, verbose_name='ID пользователя')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.MultiChoiceQuestionItem', verbose_name='Ответ')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.MultiChoiceQuestion', verbose_name='Вопрос с множественным выбором')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователя',
            },
        ),
        migrations.CreateModel(
            name='ChoiceQuestionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_value', models.TextField(verbose_name='Вариант ответа')),
                ('choice_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.ChoiceQuestion', verbose_name='Вопрос с выбором')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Вариант ответа',
            },
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz', verbose_name='Опрос'),
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True, verbose_name='ID пользователя')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.ChoiceQuestionItem', verbose_name='Ответ')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.ChoiceQuestion', verbose_name='Вопрос с одним вариантом')),
            ],
            options={
                'verbose_name': 'Ответ с одним вариантом',
                'verbose_name_plural': 'Ответ с одним вариантом',
            },
        ),
    ]
