# Generated by Django 2.2.10 on 2020-08-03 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multichoiceanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.MultiChoiceQuestionItem', verbose_name='Один из ответов'),
        ),
    ]
