# Generated by Django 2.2.10 on 2020-07-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicequestionitem',
            old_name='question',
            new_name='choice_question',
        ),
    ]
