# Generated by Django 2.2.10 on 2020-08-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200803_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicequestionitem',
            name='choice_question',
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='choices',
            field=models.ManyToManyField(to='quiz.ChoiceQuestionItem', verbose_name='Варианты ответа'),
        ),
    ]
