# Generated by Django 2.2.10 on 2020-07-31 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200731_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вопрос с несколькими вариантами',
                'verbose_name_plural': 'Вопросы с несколькими вариантами',
            },
        ),
        migrations.CreateModel(
            name='MultiChoiceQuestionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_value', models.TextField(verbose_name='Вариант ответа')),
                ('choice_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.MultiChoiceQuestion', verbose_name='Вопрос с множественным выбором')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Вариант ответа',
            },
        ),
        migrations.CreateModel(
            name='MultiChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.MultiChoiceQuestionItem', verbose_name='Ответ')),
                ('choice_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.MultiChoiceQuestion', verbose_name='Вопрос с множественным выбором')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователя',
            },
        ),
    ]
